<?php

return [
    'name' => 'DhakaFin',
    'tagline' => 'Compliant. Leak-free. In control.',
    'domain' => 'dhakafin.com',
    'email' => 'hello@dhakafin.com',
    'phone' => '+880 1XXX-XXXXXX',
    'location' => 'Motijheel, Dhaka, Bangladesh',
    'whatsapp' => '8801XXXXXXXXX',

    'stats' => [
        ['value' => 7, 'suffix' => '', 'label' => 'Practice areas under one roof'],
        ['value' => 40, 'suffix' => '+', 'label' => 'Specialist services delivered'],
        ['value' => 48, 'suffix' => 'h', 'label' => 'Proposal turnaround, guaranteed'],
        ['value' => 100, 'suffix' => '%', 'label' => 'On-time filing SLA'],
    ],

    'services' => [
        'accounting-bookkeeping' => [
            'rank' => 1,
            'medal' => 'gold',
            'title' => 'Accounting & Bookkeeping',
            'short' => 'Books that are always audit-ready, never an afterthought.',
            'description' => 'Your numbers should work as hard as you do. We run your daily books, close them monthly, and turn raw transactions into financial statements and management reports you can actually run the business on.',
            'items' => [
                'Monthly / Annual Bookkeeping',
                'Financial Statements',
                'Management Accounts',
                'Bank Reconciliation',
                'Payroll & Expense Management',
                'Accounts Receivable / Payable',
                'QuickBooks / Xero Accounting',
                'Year-end Accounts Preparation',
            ],
        ],
        'audit-assurance' => [
            'rank' => 2,
            'medal' => 'silver',
            'title' => 'Audit & Assurance',
            'short' => 'Walk into audit season like you own the room.',
            'description' => 'From statutory audit support to investigative reviews — we prepare your files, schedules and evidence so auditors find nothing but order. Independence and ICAB-compliant, every time.',
            'items' => [
                'Statutory / Annual Audit Support',
                'Financial Statement Audit',
                'Internal Audit',
                'Special / Investigative Audit',
                'Audit Documentation & Preparation',
                'Audit Readiness Review',
            ],
        ],
        'tax-services' => [
            'rank' => 3,
            'medal' => 'bronze',
            'title' => 'Tax Services',
            'short' => 'Pay what you owe. Never a taka more.',
            'description' => 'Individuals and corporates — we plan, prepare, file and defend. NBR e-filing, assessments, TDS and clearance handled with the kind of care that only comes from living inside the Income Tax Act.',
            'items' => [
                'Individual & Corporate Tax Return',
                'Tax Planning & Advisory',
                'TIN / e-TIN Services',
                'TDS / WHT Compliance',
                'Tax Assessment Support',
                'Tax Clearance & Related Services',
            ],
        ],
        'vat-services' => [
            'rank' => 4,
            'medal' => null,
            'title' => 'VAT Services',
            'short' => 'Mushak returns without the monthly migraine.',
            'description' => 'BIN to monthly return to assessment — complete VAT compliance under the VAT & SD Act, with input-output reconciliation that keeps claims clean and refunds moving.',
            'items' => [
                'BIN / VAT Registration',
                'Monthly VAT Return',
                'VAT Compliance',
                'VAT Documentation',
                'VAT Assessment / Audit Support',
                'VAT Advisory',
            ],
        ],
        'cost-efficiency' => [
            'rank' => 5,
            'medal' => null,
            'flagship' => 'CostGuard',
            'title' => 'Cost Efficiency & Internal Control',
            'short' => 'We find the money quietly leaving your business.',
            'description' => 'Our flagship CostGuard review x-rays your procurement cycle, vendors, expenses and inventory — quantifying leakage, flagging fraud risk, and designing the controls that stop it. Fixed fee, or a share of what we recover.',
            'items' => [
                'Procurement / Purchase Review',
                'Cost Leakage Detection',
                'Expense Analysis',
                'Vendor Analysis',
                'Inventory / Wastage Review',
                'Fraud-Risk & Internal Control Review',
            ],
        ],
        'corporate-compliance' => [
            'rank' => 6,
            'medal' => null,
            'title' => 'Corporate Compliance',
            'short' => 'RJSC-perfect, boardroom-ready, all year round.',
            'description' => 'Incorporation to annual returns, board minutes to share registers — the corporate housekeeping that keeps banks, investors and the RJSC happy without you touching a single form.',
            'items' => [
                'RJSC Compliance',
                'Annual Return',
                'Company Incorporation Support',
                'Corporate Records',
                'Board / Shareholder Documentation',
            ],
        ],
        'financial-advisory' => [
            'rank' => 7,
            'medal' => null,
            'title' => 'Financial & Business Advisory',
            'short' => 'Decisions backed by forecasts, not guesswork.',
            'description' => 'Budgets, cash-flow models, valuations and due diligence — a CFO-grade brain on demand for founders who plan to be much bigger than they are today.',
            'items' => [
                'Budget & Forecasting',
                'Cash-flow Management',
                'Profitability Analysis',
                'Business Valuation',
                'Financial Due Diligence',
                'Business / Financial Planning',
            ],
        ],
    ],

    'packages' => [
        [
            'name' => 'LaunchPad',
            'price' => '৳49,000',
            'period' => 'one-time',
            'tag' => 'For new ventures',
            'items' => ['Company incorporation (RJSC)', 'Trade license, TIN & BIN', 'Bank-ready share documents', 'First 3 months bookkeeping', 'Compliance calendar setup'],
        ],
        [
            'name' => 'CompliancePro',
            'price' => '৳18,000',
            'period' => '/month',
            'tag' => 'Most popular',
            'featured' => true,
            'items' => ['Monthly bookkeeping & reconciliation', 'Monthly VAT return (Mushak)', 'Payroll with TDS/VDS', 'Year-end tax & RJSC return', 'Named account manager', 'Monthly owner report'],
        ],
        [
            'name' => 'CFO+',
            'price' => '৳60,000',
            'period' => '/month',
            'tag' => 'Full finance department',
            'items' => ['Everything in CompliancePro', 'Quarterly CostGuard leak review', 'Budget, forecast & dashboards', 'Virtual CFO on call', 'Audit-season war-room support'],
        ],
    ],

    'process' => [
        ['step' => '01', 'title' => 'Discover', 'text' => 'A free 15-minute call. You talk, we listen, we map exactly what you need.'],
        ['step' => '02', 'title' => 'Diagnose', 'text' => 'We review your books, filings and processes, then send a fixed-scope proposal within 48 hours.'],
        ['step' => '03', 'title' => 'Deliver', 'text' => 'A named account team executes on a compliance calendar — monthly books, VAT, payroll, filings.'],
        ['step' => '04', 'title' => 'Defend', 'text' => 'We stand beside you at assessments, audits and renewals — all year, every year.'],
    ],

    'why' => [
        ['title' => 'Published pricing', 'text' => 'Real starting prices on the website. No "call for a quote" games.'],
        ['title' => 'Named account manager', 'text' => 'One human who knows your file, your history, your deadlines.'],
        ['title' => 'Deadline SLA', 'text' => 'Every filing on time — or the advisory work on that filing is free.'],
        ['title' => 'ICAB-aligned audit practice', 'text' => 'Statutory sign-off through our network of chartered accountants.'],
        ['title' => 'Bangla + English', 'text' => 'Documents, reports and calls in the language your team thinks in.'],
        ['title' => 'Leakage hunters', 'text' => 'The only SME-focused firm with a dedicated cost-leakage product.'],
    ],

    'testimonials' => [
        ['quote' => 'They found a ৳9 lakh gap in our purchase pipeline in the first month. The review paid for itself ten times over.', 'name' => 'Owner, trading firm', 'meta' => 'Motijheel, Dhaka'],
        ['quote' => 'Tax season used to mean two weeks of panic. Now it is one phone call and a confirmation email.', 'name' => 'Managing director, IT services', 'meta' => 'Gulshan, Dhaka'],
        ['quote' => 'Our auditor complimented the files. Our auditor. Complimented. The files.', 'name' => 'Finance lead, manufacturing SME', 'meta' => 'Narayanganj'],
    ],
];
